import { getCrewBulkUploadSummaryItems } from "../crewBulkUploadWorkspace.helpers";

describe("getCrewBulkUploadSummaryItems", () => {
  it("counts critical before commit using only open review sessions", () => {
    const items = getCrewBulkUploadSummaryItems([
      {
        id: "session-ready",
        projectId: "project-1",
        defaultAssetId: null,
        defaultAssetName: null,
        revisionNumber: 1,
        status: "READY_FOR_REVIEW",
        sourceFileName: "open.xlsx",
        sourceMimeType: "application/octet-stream",
        checksum: null,
        templateVersion: null,
        totalRows: 3,
        crewRows: 3,
        certificateRows: 0,
        criticalCount: 4,
        warningCount: 1,
        infoCount: 0,
        createdCount: 0,
        updatedCount: 0,
        skippedCount: 0,
        createdByUserId: null,
        committedByUserId: null,
        discardedByUserId: null,
        committedAt: null,
        discardedAt: null,
        createdAt: "2026-04-20T08:00:00.000Z",
        updatedAt: "2026-04-20T08:00:00.000Z",
      },
      {
        id: "session-committed",
        projectId: "project-1",
        defaultAssetId: null,
        defaultAssetName: null,
        revisionNumber: 1,
        status: "COMMITTED",
        sourceFileName: "done.xlsx",
        sourceMimeType: "application/octet-stream",
        checksum: null,
        templateVersion: null,
        totalRows: 3,
        crewRows: 3,
        certificateRows: 0,
        criticalCount: 12,
        warningCount: 0,
        infoCount: 0,
        createdCount: 1,
        updatedCount: 2,
        skippedCount: 0,
        createdByUserId: null,
        committedByUserId: null,
        discardedByUserId: null,
        committedAt: "2026-04-20T09:00:00.000Z",
        discardedAt: null,
        createdAt: "2026-04-20T08:00:00.000Z",
        updatedAt: "2026-04-20T09:00:00.000Z",
      },
      {
        id: "session-discarded",
        projectId: "project-1",
        defaultAssetId: null,
        defaultAssetName: null,
        revisionNumber: 1,
        status: "DISCARDED",
        sourceFileName: "discarded.xlsx",
        sourceMimeType: "application/octet-stream",
        checksum: null,
        templateVersion: null,
        totalRows: 3,
        crewRows: 3,
        certificateRows: 0,
        criticalCount: 7,
        warningCount: 0,
        infoCount: 0,
        createdCount: 0,
        updatedCount: 0,
        skippedCount: 0,
        createdByUserId: null,
        committedByUserId: null,
        discardedByUserId: null,
        committedAt: null,
        discardedAt: "2026-04-20T10:00:00.000Z",
        createdAt: "2026-04-20T08:00:00.000Z",
        updatedAt: "2026-04-20T10:00:00.000Z",
      },
    ]);

    const criticalItem = items.find(
      (item) => item.label === "Critical before commit",
    );

    expect(criticalItem?.value).toBe("4");
  });
});
